# Site settings
title: Blog
subtitle: [ 雲木]
keywords: Blog
description: 苟日新，日日新，又日新。微信公众号：oukohou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanzhixiaozhu.top/" # 你的域名
page_no_title: "Who's blog?" # 文章无标题时默认显示内容
beian: # "备案号"
author: 雲木
email: don952509@foxmail.com

# Build settings
markdown: kramdown
encoding: utf-8
plugins: [jekyll-paginate]
#gem 'jekyll-paginate', group: :jekyll_plugins
#permalink: /:year/:month/:day/:title/
#exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
#plugins:
  #- jekyll-paginate
  #- jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.

#highlighter: rouge
#kramdown:
  #input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: #true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接

  - title: oukohou's blog
    url: https://www.oukohou.wang/
  - title: konghy's blog
    url: https://blog.konghy.cn/
  - title: yonsm's blog 
    url: https://yonsm.github.io/


# Google Analytics
ga_track_id: 'UA-130856615-1'            # Format: UA-xxxxxx-xx
ga_domain: sanzhixiaozhu.top              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/ycjxjrlx


valine:
  enable: true
  app_id:  JUGJMk0HRqnksDAdy57b7Ktk-gzGzoHsz
  app_key: jJnOosg7SxYehjFNvLSpwl0u
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
  guest_info: nick,mail,link
  pageSize: 10
